BookList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookListApp.urls')),
]

BookListApp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from BookListApp import views
app_name = 'BookListApp'
urlpatterns = [
    path(
        '',
        views.MainListView.as_view(),
        name = 'home',
    ),
    path(
        'delete/<int:pk>/',
        views.DeleteBookView.as_view(),
        name = 'delete',
    ),
    path(
        'update/<int:pk>/',
        views.UpdateBookView.as_view(),
        name = 'update',
    ),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookListApp/models.py
from enum import Enum
from django.db import models

# Create your models here.

class BookType(Enum):
    NOV = "Novel"
    DOC = "Documentation"
    OTH = "Other"

class Book(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)

    date_modified = models.DateTimeField(auto_now=True)

    title = models.CharField(
        max_length = 40,
        null = False,
        blank = False,
    )

    author = models.CharField(
        max_length = 100,
        null = False,
        blank = False,
    )

    date_published = models.DateField(null=True,blank=True,)

    number_of_pages = models.IntegerField(null=True,blank=True,)

    NOV = 'NOV'
    DOC = 'DOC'
    OTH = 'OTH'

    type_of_book = models.CharField(
        max_length = 3,
        choices = (
            (NOV, 'Novel'),
            (DOC, 'Documentation'),
            (OTH, 'Other'),
        ),
        null=True,
        blank=True,
    )

BookListApp/forms.py
from django import forms
from BookList import settings
from BookListApp import models

class BookBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookBaseForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta:
        model = models.Book
        fields = '__all__'

class BookCreationForm(BookBaseForm):
    """Creation Form"""
    def __init__(self, *args, **kwargs):
        super(BookCreationForm, self).__init__(*args, **kwargs)
        self.fields.get("date_published").widget.attrs["placeholder"]="Date published (dd MM, yyyy)"
    class Meta(BookBaseForm.Meta):
        widgets = {
            'date_published':forms.DateInput(format="%d %B, %Y"),
        }
    class Media:
        css = {
            'all':(
                'BookListApp/css/book-add.css',
                'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css',
            )
        }

        js = (
            'BookListApp/js/book-add.js',
            'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js',
        )


class BookUpdateForm(BookBaseForm):
    """Update Form"""
    class Meta(BookBaseForm.Meta):
        widgets = {
            'date_published':forms.DateInput(format="%d %B, %Y"),
        }
    class Media:
        css = {
            'all':(
                'BookListApp/css/book-update.css',
                'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css',
            )
        }

        js = (
            'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js',
        )

BookListApp/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin



from BookListApp import models, forms
# Create your views here.


class MainListView(SuccessMessageMixin, CreateView):
    template_name = 'BookListApp/main-page.html'
    model=models.Book
    form_class = forms.BookCreationForm
    success_url = reverse_lazy('BookListApp:home')
    success_message = 'Book Added'

    def get_context_data(self,**kwargs):
        context = super(MainListView,self).get_context_data(**kwargs)
        #context for the book list
        context["Books"] = self.model.objects.all();
        #context for navigation
        context["Breadcrumbs"] = [
            ("Home", reverse_lazy('BookListApp:home')),
        ]
        return context

    def form_invalid(self, form):
        html_message=""

        for idx, field_messages in form.errors.items():
            for message in field_messages:
                html_message = html_message + message +"\n"

        messages.add_message(
            request=self.request,
            level=messages.ERROR,
            message=html_message,
            fail_silently=True,
        )

        return super(MainListView, self).form_invalid(form);

class DeleteBookView(DeleteView):
    model = models.Book
    success_url = reverse_lazy('BookListApp:home')

class UpdateBookView(SuccessMessageMixin, UpdateView):
    model = models.Book
    template_name = "BookListApp/book-update.html"
    form_class = forms.BookUpdateForm
    success_url = reverse_lazy('BookListApp:home')
    success_message = 'Book update success'

    def get_context_data(self,**kwargs):
        context = super(UpdateBookView,self).get_context_data(**kwargs)
        #context for navigation
        context["Breadcrumbs"] = [
            ("Home", reverse_lazy('BookListApp:home')),
            ("Edit", reverse_lazy('BookListApp:update'))
        ]
        return context

BookListApp/templates/BookListApp/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% block title %}
      <title>Home</title>
    {% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'BookListApp/css/base.css' %}" rel="stylesheet">

    {% block stylesheet %}

    {% endblock %}

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}

    {% block form-media %}
      {{form.media}}
    {% endblock %}

  </head>

  <body>
    {% block content-header %}
      {% include "BookListApp/header.html" with Breadcrumbs=Breadcrumbs %}
    {% endblock %}
    {% block content-main %}
      <main>

      </main>
    {% endblock %}
    {% block content-footer %}
      <footer>

      </footer>
    {% endblock %}

    {% if messages %}
      {% include "BookListApp/message.html" with messages=messages%}
    {% endif %}

    {% block content-scripts %}
    {% endblock %}
  </body>
</html>

BookListApp/templates/BookListApp/book-create.html
<div class="card mb-3">
  <div class="overlay">
    <a href="#"  class="btn btn-primary btn-add">Add Book</a>
  </div>
  <form action="{% url 'BookListApp:home' %}" class="blur" method="post">
    {% csrf_token %}
    <h4 class="card-header">{{ form.title }}</h4>
    <div class="card-body">
      <div class="form-group mb-1">
        {{form.author }}
      </div>
      <div class="form-group mb-1">
        {{form.type_of_book}}
      </div>
      <div class="form-group mb-1">
        {{form.date_published}}
      </div>
      <div class="form-group mb-1">
        {{form.number_of_pages}}
      </div>
    </div>
    <div class="card-footer">
      <input type="submit" name="submit" value="Submit" class="btn btn-primary"/>
      <input type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-cancel"/>
    </div>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    //button to remove overlay
    $(".btn-add").on("click", function(e){
      e.preventDefault();
      var parrent = $(this).parent(".overlay").hide('fast');
      parrent.siblings("form").toggleClass("blur");
    });

    $(".btn-cancel").on("click", function(e){
      e.preventDefault();
      var form = $(this).closest("form").toggleClass("blur");
      form.find("input[type=text], textarea").val("");
      form.find("select").prop("selectedIndex",0);
      form.siblings(".overlay").show('fast');
    });

    // bind with bootstrap-datepicker plugin
    $("#id_date_published").datepicker({
      format:"dd MM, yyyy",
      orientation: "bottom",
      startView: "decade",
      showWeekDays: false,
      autoclose: true,
    });
  });
</script>

BookListApp/templates/BookListApp/book-delete-confirm.html
  <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close d-none" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                </div>

                <div class="modal-body">
                    <p>You are about to delete one Book, this procedure is irreversible.</p>
                    <p>Do you want to proceed?</p>
                    <p class="debug-url"></p>
                </div>

                <div class="modal-footer">
                  <button class="btn btn-danger btn-ok" data-dismiss="modal">Delete</button>
                  <button id="btn-cancel-delete" type="button" class="btn btn-default btn-cancel" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

BookListApp/templates/BookListApp/book-update.html
{% extends "BookListApp/base.html" %}
{% block title %}
  <title>Edit</title>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
  $(document).ready(function() {
    $("#id_date_published").datepicker({
      format:"dd MM, yyyy",
      orientation: "bottom",
      startView: "decade",
      showWeekDays: false,
      autoclose: true,
    });
  });
</script>
{% endblock %}

{% block content-main %}
<main>
  <div class="container form-container">
    <form class="form-update" method="post">
      {% csrf_token %}
      <div class="form-group">
        {{ form.title }}
      </div>
      <div class="form-group">
        {{ form.author }}
      </div>
      <div class="form-group">
        {{ form.date_published }}
      </div>
      <div class="form-group">
        {{ form.type_of_book }}
      </div>
      <div class="form-group">
        {{ form.number_of_pages }}
      </div>
      <input type="submit" name="submit" class="btn btn-primary" value="Save"/>
      <a href="{% url 'BookListApp:home' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
</main>
{% endblock %}

BookListApp/templates/BookListApp/book-view.html
<div class="card mb-3">
  <h4 class="card-header">{{Book.title|title}}</h4>
  <div class="card-body">
    <h5 class="card-title">by: {{Book.author | title}}</h5>
    <p>Category: {{Book.get_type_of_book_display}} </p>
    <p>Published: {{Book.date_published|date:"d F, Y"|default:"Unavailable"}}</p>
    <p>{% if Book.number_of_pages %}{{Book.number_of_pages}} pages{% endif %}
    </p>

  </div>
  <div class="card-footer">
    <a href="{%url "BookListApp:update" Book.pk %}" class="btn btn-primary">Edit</a>
    <a data-target="#confirm-delete" href="{%url "BookListApp:delete" Book.id %}" data-toggle="modal" class="btn btn-secondary btn-delete">Delete</a>
  </div>
</div>

BookListApp/templates/BookListApp/bookview.html
<div class="card">
  <h4 class="card-header">{{Book.title}}</h4>
  <div class="card-body">
    <h5 class="card-title">by: {{Book.author | title}}</h5>
    <p>Category: {{Book.get_type_of_book_display}} </p>
    <p>Published: {{Book.date_published}}</p>
    <a href="{%url "BookListApp:delete" Book.id %}" class="btn btn-primary btn-delete">Delete</a>
  </div>
</div>

BookListApp/templates/BookListApp/breadcrumb.html
<ol class="breadcrumb">
  {% for nav in navigations %}
  <li class = "breadcrumb-item"><a hreff="/{{nav}}">{{nav}}</a></li>
    {% if forloop.last %}
  <li class = "breadcrumb-item active" aria-current="page">{{nav}}</li>
    {% endif %}
  {% endfor %}
</ol>

BookListApp/templates/BookListApp/header.html
<header class="fixed-top">
  <ol class="breadcrumb" aria-label="">
    {% for Breadcrumb, Link in Breadcrumbs %}
      {% if forloop.last %}
      <li class = "breadcrumb-item active" aria-current="page">{{Breadcrumb}}</li>
      {% else %}
      <li class = "breadcrumb-item"><a href="{{ Link }}">{{Breadcrumb}}</a></li>
      {% endif %}
    {% endfor %}
  </ol>
</header>

BookListApp/templates/BookListApp/main-page.html
{% extends "BookListApp/base.html" %}
{% load static%}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static "BookListApp/css/main-page.css" %}">
{% endblock %}

{% block scripts %}
  <script src="{% static 'BookListApp/js/cookie-manager.js' %}"></script>
  <script src="{% static 'BookListApp/js/book-delete.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.btn-delete').asDeleteButton();
      $('#confirm-delete').asConfirmModal();
    });
  </script>
{% endblock %}

{% block content-main %}
<main>
    <div class="container container-main">
      {% include "BookListApp/book-create.html" with form=form %}

      {% for Book in Books %}
        {% include "BookListApp/book-view.html" with Book=Book %}
      {% endfor %}
    </div>
</main>
{% endblock %}

{% block content-footer %}
  {% include "BookListApp/book-delete-confirm.html" %}
{% endblock %}

BookListApp/templates/BookListApp/message.html
  <!-- notification container -->
  <div class="notification-container">
    {% for message in messages %}
    <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
      {{message|capfirst}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  </div>
  <script type="text/javascript">
    $(".alert-dismissible").fadeTo(5000, 500).slideUp(500, function(){
        $(".notification-top").slideUp(500);
    });
  </script>